language: python
python:
  - "3.8"

before_install:
  - pip install pycodestyle

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - python -m pytest tests/
  - pycodestyle src/ --ignore=E722,E501,E402