language: python
python:
  - "3.8"

before_install:
  - pip install pycodestyle

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - python -m pytest tests/
  - coverage run --source="app/" -m pytest
  - pycodestyle app/ --ignore=E722,E501,E402
