"""changed tablenames

Revision ID: 154a639c354b
Revises: 27168625dccc
Create Date: 2021-05-03 16:07:01.109406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154a639c354b'
down_revision = '27168625dccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('average_salary', sa.Float(precision=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('salary', sa.Float(precision=16), nullable=False),
    sa.Column('departament', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['departament'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('employee')
    op.drop_table('departament')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departament',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=True),
    sa.Column('title', sa.VARCHAR(length=120), nullable=False),
    sa.Column('average_salary', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('employee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('salary', sa.FLOAT(), nullable=False),
    sa.Column('departament', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['departament'], ['departament.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('employees')
    op.drop_table('departments')
    # ### end Alembic commands ###
