"""initial migrate

Revision ID: 27168625dccc
Revises: 
Create Date: 2021-05-01 16:01:49.308212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27168625dccc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('average_salary', sa.Float(precision=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('salary', sa.Float(precision=16), nullable=False),
    sa.Column('departament', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['departament'], ['departament.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('departament')
    # ### end Alembic commands ###
